# Generated by Django 2.2.1 on 2019-05-18 20:17

import auth_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cc', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('punto_venta', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
                ('rol_administrador', models.BooleanField(default=False)),
                ('rol_inventario', models.BooleanField(default=False)),
                ('rol_cajero', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', auth_api.models.UserManager()),
            ],
        ),
    ]
